---
title: "llm_table_repeats"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    number_sections: true
vignette: >
  %\VignetteIndexEntry{llm_table_repeats}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
#| label: "rsetup"
#| include: true
#| eval: true
library(reticulate)
use_virtualenv("/Users/work/pyollama", required = TRUE)
```

```{r}
#| label: "create_example1"
#| include: true
#| eval: true
#| df-print: default
library(kableExtra)
library(synthpop)
library(janitor)
library(knitr)
library(gt)
library(dplyr)

# 1. Create the table with totals using janitor
my_table1_object <- SD2011 %>%
  tabyl(sex, edu,show_na=FALSE) %>%
  adorn_totals(where = c("row", "col")) %>% # Adds both Row and Column totals
  
  # 2. Pass to kable
  kable(caption = "Education Level by Sex with Totals",format="pipe") #%>%
  #kable_styling(full_width = F) %>%
  
  # 3. Apply your specific styling
  #column_spec(1, bold = T, color = "blue") %>%
  # Optional: Bold the last row (Grand Total)
  #row_spec(nrow(tabyl(SD2011, sex, edu)) + 1, bold = T) 

print(my_table1_object)


```



```{r}
#| label: "data set for passing"
#| include: true
#| eval: true
library(jsonlite)
## Instruction: You are a clinical data analyst. Analyze the following patient records and answer the query accurately.

thedata<-toJSON(head(SD2011),pretty=TRUE)
Nint<-2L
r_to_py(Nint)
```

```{python}
print(f"N={r.Nint}\n")
N=r.Nint
```



```{python}
#| label: "py1"
#| include: true
#| eval: true

prompt = """
Instruction: You are an expert statistician and programmer. Analyze the following patient records and answer the query accurately. 

Data:
[
  {
    "sex": "FEMALE",
    "age": 57,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Lubuskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "services for the population and transport services",
    "socprof": "RETIRED",
    "unempdur": 0,
    "income": 800,
    "marital": "MARRIED",
    "mmarr": 10,
    "ymarr": 1979,
    "ls": "PLEASED",
    "depress": 6,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 6,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 170,
    "weight": 89,
    "bmi": 30.7958
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "income": 350,
    "marital": "SINGLE",
    "ls": "MOSTLY SATISFIED",
    "depress": 0,
    "trust": "IT`S DIFFICULT TO TELL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 4,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 187,
    "weight": 82,
    "bmi": 23.4493
  },
  {
    "sex": "FEMALE",
    "age": 18,
    "agegr": "16-24",
    "placesize": "URBAN 500,000 AND OVER",
    "region": "Mazowieckie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 0,
    "trust": "MOST PEOPLE CAN BE TRUSTED",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 20,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 50,
    "bmi": 18.3655
  },
  {
    "sex": "FEMALE",
    "age": 78,
    "agegr": "65+",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "PRIMARY/NO EDUCATION",
    "eduspec": "no specialisation",
    "socprof": "RETIRED",
    "unempdur": -8,
    "income": 900,
    "marital": "WIDOWED",
    "mmarr": 8,
    "ymarr": 1958,
    "msepdiv": 12,
    "ysepdiv": 1997,
    "ls": "MIXED",
    "depress": 16,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "NO",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 0,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 160,
    "weight": 78,
    "bmi": 30.4687
  },
  {
    "sex": "FEMALE",
    "age": 54,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Zachodnio-pomorskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "agriculture, forestry, fishing",
    "socprof": "SELF-EMPLOYED",
    "unempdur": -8,
    "income": 1500,
    "marital": "MARRIED",
    "mmarr": 6,
    "ymarr": 1980,
    "ls": "MOSTLY SATISFIED",
    "depress": 4,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 6,
    "smoke": "YES",
    "nociga": 20,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 158,
    "weight": 50,
    "bmi": 20.0288
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "URBAN 100,000-200,000",
    "region": "Slaskie",
    "edu": "SECONDARY",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": 0,
    "income": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 5,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 10,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 65,
    "bmi": 23.8751
  }
] 

Query: Write R code to create the table given below.

Table: Education Level by Sex with Totals

|sex    | PRIMARY/NO EDUCATION| VOCATIONAL/GRAMMAR| SECONDARY| POST-SECONDARY OR HIGHER| Total|
|:------|--------------------:|------------------:|---------:|------------------------:|-----:|
|MALE   |                     |                   |          |                         |      |
|FEMALE |                     |                   |          |                         |      |
|Total  |                     |                   |          |                         |      |

Each cell in the table is a count. This table can be created with the R libraries: janitor; knitr; kableExtra, dplyr. Other or additional R libraries may also be used or needed. The data set is a data.frame called "SD2011". Missing value or NA in the data should be removed and not included in the table outputs. The table should be in pipe or plain text format. Return the R code as JSON in an element called code. Check the code. Be concise.


"""
```

```{python}
#| label: "py2"
#| include: true
#| eval: true
#| 

import ollama
import json
#print(prompt)
model_name = 'qwen3-coder:30b' #'phi4:latest'
#model_name = 'phi4:latest'

results1 = []
#resandprompt = []
for i in range(N):
    print(i)
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'system', 'content': 
          """You are a helpful assistant that responds in JSON. 
             The JSON response should have a structure like this: {'code': ['the R code generated']}
             """
        },
                  {'role': 'user', 'content': prompt}],
        keep_alive='120m'
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    
    #print(f"iter={i} {data['code']}\n")
    results1.append(data)
    #resandprompt.append(f"{prompt2a}\n{data['code']}")

```


```{python}
#| label: "py3"
#| include: true
#| eval: true
#| 

import ollama
import json
#print(prompt)
#model_name = 'qwen3:30b' #'phi4:latest'
model_name = 'phi4:latest'

results2 = []
#resandprompt = []
for i in range(N):
    print(i)
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'system', 'content': 
          """You are a helpful assistant that responds in JSON. 
             The JSON response should have a structure like this: {'code': ['the R code generated']}
             """
        },
                  {'role': 'user', 'content': prompt}],
        keep_alive='120m'
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    
    #print(f"iter={i} {data['code']}\n")
    results2.append(data)
    #resandprompt.append(f"{prompt2a}\n{data['code']}")

```


```{r}
results1<-py$results1
results2<-py$results2

save(results1,file="qwen1_50.RData")
save(results2,file="qwen2_50.RData")

```


```{r}
library(tidyr)
safe_run<- function(code) {
  tryCatch({
    all_results <- eval(parse(text = code));
    print(all_results)
    return(all_results)
  }, error = function(e) {
    paste("Error in generated code:", e$message)
  })
}

good_i<-NULL;
bad<-NULL;
for(i in 1:length(py$results1)){
cat("i=",i,"\n")
  res<-print(safe_run(py$results1[[i]]$code))
  print(nchar(res))
  if(length(res)==0){good_i<-c(good_i,i)
  } else {bad<-c(res,bad)}
    
  }

#safe_run(py$results1[2])
#save.image("qwen100.RData")
```

```{r}
#safe_run(py$results1[1][[1]]$code)

```
## the end



